name: Go release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-gnu-linux:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    name: Release - GNU/Linux | ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          go build -o srmgo
          tar -zcf securerm-go-linux_${{ matrix.arch }}.tar.gz srmgo LICENSE NOTICE

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: securerm-go-linux_${{ matrix.arch }}.tar.gz

  build-windows:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    name: Release - Windows | ${{ matrix.arch }}
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          go build -o srmgo.exe
          powershell -command "Compress-Archive -Path 'srmgo.exe', 'LICENSE', 'NOTICE' -DestinationPath 'securerm-go-windows.zip'"


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: securerm-go-windows_${{ matrix.arch }}.zip

  build-macos:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    name: Release - MacOS | ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          go build -o srmgo
          tar -zcf securerm-go-macos_${{ matrix.arch }}.tar.gz srmgo LICENSE NOTICE

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: securerm-go-macos_${{ matrix.arch }}.tar.gz
