name: Go test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test-run-unix:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        arch:
          - amd64
          - arm64
    name: Test run - ${{ matrix.os }} | ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Test run
        run: |
          go build -o srmgo
          mkdir temp/
          echo 'Delete me!' > temp/temp_file.txt
          ./srmgo -rv temp/

  test-run-windows:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    name: Test run - windows | ${{ matrix.arch }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Test run
        run: |
          go build -o srmgo.exe
          mkdir temp\
          echo 'Delete me!' > temp\temp_file.txt
          .\srmgo.exe -rv temp\
